<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Customize\Repository;

use Eccube\Repository\AbstractRepository;
use Doctrine\Persistence\ManagerRegistry as RegistryInterface;
use Eccube\Doctrine\Query\Queries;
use Eccube\Entity\Cart;
use Eccube\Entity\Customer;
use Customize\Repository\QueryKey;

/**
 * CartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRepository extends AbstractRepository
{
    /**
     * @var Queries
     */
    protected $queries;
    
    /**
     * OrderRepository constructor.
     *
     * @param RegistryInterface $registry
     * @param Queries $queries
     */
    public function __construct(RegistryInterface $registry, Queries $queries)
    {
        parent::__construct($registry, Cart::class);
        $this->queries = $queries;
    }
    
    /**
     * @param  \Eccube\Entity\Customer $Customer
     * @param  \Eccube\Entity\Cart $Cart
     * @param  \Eccube\Entity\CartItem $CartItem
     *
     * @return QueryBuilder
     */
    public function getQueryBuilderByCustomer(Customer $Customer)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->addSelect(['ci'])
        ->leftJoin('c.CartItems', 'ci')
            //->where('c.CartItems = :CartItem')
            //->setParameter('CartItem', $CartItem)
            ->where('c.Customer = :Customer')
            ->setParameter('Customer', $Customer)
            ->andWhere('c.id = :cart_id')
            ->setParameter('cart_id', 51);

        // Order By
        $qb->addOrderBy('c.id', 'ASC');

        return $this->queries->customize(QueryKey::CART_SEARCH_BY_CUSTOMER, $qb, ['customer' => $Customer]);
    }
}
