<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Customize\Repository;

use Eccube\Repository\AbstractRepository;
use Doctrine\Persistence\ManagerRegistry as RegistryInterface;
use Eccube\Entity\CartItem;
use Eccube\Doctrine\Query\Queries;
use Customize\Repository\QueryKey;

/**
 * CartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartItemRepository extends AbstractRepository
{
    /**
     * @var Queries
     */
    protected $queries;
    
    /**
     * OrderRepository constructor.
     *
     * @param RegistryInterface $registry
     * @param Queries $queries
     */

    public function __construct(RegistryInterface $registry, Queries $queries)
    {
        parent::__construct($registry, CartItem::class);
        $this->queries = $queries;
    }

    /**
     * @param  \Eccube\Entity\Cart $Cart
     * @param  \Eccube\Entity\CartItem $CartItem
     *
     * @return QueryBuilder
     */
    public function getQueryBuilderByCustomer($cart_id)
    {
        $qb = $this->createQueryBuilder('ci')
            ->where('ci.cart_id = :cart_id')
            ->setParameter('cart_id', $cart_id);

        // Order By
        $qb->addOrderBy('ci.id', 'ASC');

        return $this->queries->customize(QueryKey::CART_SEARCH_BY_CUSTOMER, $qb, ['cart_id' => $cart_id]);
    }
}
