<?php

namespace Customize\Repository;

use Doctrine\Persistence\ManagerRegistry;
use Eccube\Repository\AbstractRepository;
use Customize\Entity\SchoolAuth;

/**
 * SchoolAuthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolAuthRepository extends AbstractRepository
{
    /**
     * SchoolAuthRepository constructor.
     *
     * @param ManagerRegistry $registry
     */
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, SchoolAuth::class);
    }

    /**
     * @param int $id
     *
     * @return null|SchoolAuth
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }

    /**
     * @param string $code
     *
     * @return null|SchoolAuth
     */
    public function getWithCode($code = null)
    {
        if (empty($code)) return null;
        $result = $this->findBy(['code' => $code]);
        return count($result) > 0 ? $result[0] : null;

    }

    /**
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getQueryBuilderAll()
    {
        $qb = $this->createQueryBuilder('n');
        /* $qb->orderBy('n.publish_date', 'DESC') */
        /*     ->addOrderBy('n.id', 'DESC'); */
        $qb->addOrderBy('n.id', 'DESC');

        return $qb;
    }

    /**
     * レシピ考案者を登録します.
     *
     * @param News $News
     *
     * @throws ForeignKeyConstraintViolationException 外部キー制約違反の場合
     * @throws DriverException SQLiteの場合, 外部キー制約違反が発生すると, DriverExceptionをthrowします.
     */
    public function delete($SchoolAuth)
    {
        $em = $this->getEntityManager();
        $em->remove($SchoolAuth);
        $em->flush();
    }
}
