<?php

namespace Customize\Repository;

use Doctrine\Persistence\ManagerRegistry;
use Eccube\Repository\AbstractRepository;
use Customize\Entity\School;

/**
 * SchoolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolRepository extends AbstractRepository
{
    /**
     * SchoolRepository constructor.
     *
     * @param ManagerRegistry $registry
     */
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, School::class);
    }

    /**
     * @param int $id
     *
     * @return null|School
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }

    /**
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getQueryBuilderAll()
    {
        $qb = $this->createQueryBuilder('n');
        /* $qb->orderBy('n.publish_date', 'DESC') */
        /*     ->addOrderBy('n.id', 'DESC'); */
        $qb->addOrderBy('n.id', 'DESC');

        return $qb;
    }

    /**
     * レシピ考案者を登録します.
     *
     * @param News $News
     *
     * @throws ForeignKeyConstraintViolationException 外部キー制約違反の場合
     * @throws DriverException SQLiteの場合, 外部キー制約違反が発生すると, DriverExceptionをthrowします.
     */
    public function delete($School)
    {
        $em = $this->getEntityManager();
        $em->remove($School);
        $em->flush();
    }
}
